<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Classes.aspx.cs" Inherits="Honors_Project.Admin.Classes" MasterPageFile="~/Master/Site.Master" Title="Manage Classes" %>

<asp:Content ID="ContentID1" ContentPlaceHolderID="Main" runat="server">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="True" DataSourceID="ClassSrc" DataKeyNames="ID" AutoGenerateDeleteButton="true"/>
    <asp:SqlDataSource ID="ClassSrc" runat="server" ConnectionString="<%$ ConnectionStrings:constr %>"
        SelectCommand="SELECT * FROM Classes"
        DeleteCommand="DELETE FROM Classes WHERE ID = @ID">
        <DeleteParameters>
            <asp:Parameter Name="ID" Type="Int32" />
        </DeleteParameters>
    </asp:SqlDataSource>
</asp:Content>
